### PR TITLE
Fixing typos in the documentation

### PR DESCRIPTION
**Pull request by jeffm14vt**

### CODE REVIEW

**Comment by jeffm14vt** [comment]
Not sure why the build's failing

**Comment by JoeyZwicker** [comment]
Hi @jeffm14vt Thanks for the PR and signing the CLA. 

CI fails for external contributors because it needs creds. No big deal, we'll run CI for you and merge this in once it passes. Thanks for catching the typo, so there's no actual reason CI will a problem.

**Comment by dwhitena** [comment]
CI here: https://github.com/pachyderm/pachyderm/pull/2554

**Comment by dwhitena** [comment]
@sjezewski Do you know why the CI is failing for this (in PR https://github.com/pachyderm/pachyderm/pull/2554). I'm getting the following:

```
# github.com/pachyderm/pachyderm/src/server/pps/cmds
src/server/pps/cmds/cmds.go:784:17: undefined: docker
src/server/pps/cmds/cmds.go:788:13: undefined: docker
src/server/pps/cmds/cmds.go:800:35: undefined: docker
src/server/pps/cmds/cmds.go:807:17: undefined: docker
src/server/pps/cmds/cmds.go:809:16: undefined: docker
src/server/pps/cmds/cmds.go:813:23: undefined: docker
src/server/pps/cmds/cmds.go:827:3: undefined: docker
make: *** [install] Error 2
```

Once we get that taken care of we can merge this I think.

**Comment by dwhitena** [comment]
@jeffm14vt was there a reason that `github.com/fsouza/go-dockerclient` was removed here. I think it's causing CI to fail.

**Comment by jeffm14vt** [comment]
@dwhitena Sorry about that, not sure why it was omitted.

**Comment by dwhitena** [comment]
Thanks @jeffm14vt. Rerunning CI.

**Comment by dwhitena** [comment]
Thanks! LGTM.
